version: '3'
services: 
    node:
        build: .
        restart: always
        ports: 
            - ${PORT}:${PORT}
        depends_on: 
            - postgres
        environment:
            PORT: ${PORT}
        networks: 
            - my_network
        volumes:
            - ./log:/usr/app/log
            - ./src:/usr/app/src
    postgres:
        build: ./database/
        restart: always
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        environment:
            PORT: ${POSTGRES_PORT}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_PORT: ${POSTGRES_PORT}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        networks: 
            - my_network
        volumes: 
            - ./pg_data:/var/lib/postgresql/data
networks: 
    my_network:
        driver: bridge