version: '3'
services: 
    node:
        build: .
        restart: always
        ports: 
            - ${PORT}:${PORT}
        depends_on: 
            - postgres
        environment:
            PORT: ${PORT}
        networks: 
            - my_network
        volumes:
            - ./src/log:/usr/app/src/log
            - ./src:/usr/app/src
    postgres:
        build: ./database/
        restart: always
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        environment:
            PORT: ${POSTGRES_PORT}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_PORT: ${POSTGRES_PORT}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        networks: 
            - my_network
        volumes: 
            - ./pg_data:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
        ports:
            - ${PGADMIN_PORT}:80
        volumes:
            - ./pgadmin:/var/lib/pgadmin
        depends_on:
            - postgres
        networks:
            - my_network
networks: 
    my_network:
        driver: bridge